### ISSUE TITLE
Disabling home button through an app using android hacks

### ISSUE THREAD

**Issue by suadalshammri** [smargav/android-hacks#1]
I am trying to create an app that disables the home button using android hacks https://github.com/smargav/android-hacks/wiki/Android-Hacks
I found a link, I followed it but I got errors.I added WRITE SETTINGS and WRITE SECURE SETTINGS permissions in the Manifest file and I have a rooted device but its not working.

This is the mainActivity:

public class MainActivity extends AppCompatActivity {
    public static final String DEVICE_PROVISIONED = Settings.Global.DEVICE_PROVISIONED;
    public static final String USER_SETUP_COMPLETE = "user_setup_complete";

    @Override
    protected void onCreate(Bundle icicle) {
       // super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        super.onCreate(icicle);

        DevicePolicyManager policyManager = (DevicePolicyManager) getSystemService(Context.DEVICE_POLICY_SERVICE);
       //policyManager.setDeviceOwner("com.suad.myapplication", "MyApplication");

        // Add a persistent setting to allow other apps to know the device has been provisioned.
        Settings.Global.putInt(getContentResolver(), Settings.Global.DEVICE_PROVISIONED, 1);
        Settings.Secure.putInt(getContentResolver(),USER_SETUP_COMPLETE, 1);
       /* try {
            Process process = Runtime.getRuntime().exec(new String[] { "su", "-c", USER_SETUP_COMPLETE});
        } catch (IOException e) {
            e.printStackTrace();
        }*/

        // remove this activity from the package manager.
        PackageManager pm = getPackageManager();
        ComponentName name = new ComponentName(this, MainActivity.class);
        pm.setComponentEnabledSetting(name, PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP);

        // terminate the activity.
        finish();
    }
}

**Comment by amsurana** [comment]
This code should work, if your app is signed using system signature or installed in /system/priv-app folder. 
> Settings.Secure.putInt(getContentResolver(),USER_SETUP_COMPLETE, 1);

The shell command should be of this format:
> "su", "-c", "settings put secure user_setup_complete 0"


There are chances that you might have to reboot the device to ensure settings is applied.
